# Generated by Django 4.1.7 on 2023-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('post_body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
